swagger: '2.0'
info:
  title: TODO API
  description: API for managing TODO tasks
  version: 1.0.0
basePath: /tasks
schemes:
  - http
paths:
  /:
    post:
      tags:
        - Tasks
      description: Create a new task
      parameters:
        - in: body
          name: body
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
            required:
              - title
      responses:
        201:
          description: Task created
          schema:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              description:
                type: string
              created_at:
                type: string
              updated_at:
                type: string
  /:
    get:
      tags:
        - Tasks
      description: Get list of all tasks
      responses:
        200:
          description: A list of tasks
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                description:
                  type: string
                created_at:
                  type: string
                updated_at:
                  type: string
  /{id}:
    get:
      tags:
        - Tasks
      description: Get a task by its ID
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: Task details
          schema:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              description:
                type: string
              created_at:
                type: string
              updated_at:
                type: string
        404:
          description: Task not found
    put:
      tags:
        - Tasks
      description: Update a task by its ID
      parameters:
        - name: id
          in: path
          type: integer
          required: true
        - in: body
          name: body
          schema:
            type: object
            properties:
              title:
                type: string
              description:
                type: string
      responses:
        200:
          description: Task updated
          schema:
            type: object
            properties:
              id:
                type: integer
              title:
                type: string
              description:
                type: string
              created_at:
                type: string
              updated_at:
                type: string
        404:
          description: Task not found
    delete:
      tags:
        - Tasks
      description: Delete a task by its ID
      parameters:
        - name: id
          in: path
          type: integer
          required: true
      responses:
        200:
          description: Task deleted successfully
          schema:
            type: object
            properties:
              message:
                type: string
        404:
          description: Task not found
